name: Sphinx Build
on:
  push:
    branches: [ "master" ]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: ${{github.workspace}}/docs/
